#ifndef ERRCODE_H
#define ERRCODE_H

typedef enum {
    ERR_NONE = 0,
    ERR_SLEEP_FAILED,
    ERR_TICK_TIMEOUT,
    ERR_TIME_FUNC,
    ERR_INVALID_ARGUMENT,
    ERR_UNKNOWN,
    ERR_NO_SUPPORTED_OPCODE,
    ERR_FILE_NOT_FOUND,
    ERR_ROM_TOO_LARGE,
    ERR_THREAD_CREATION_FAILED,


    ERR_FILE_READ_FAILED,
    ERR_PATH_TOO_LONG,
    ERR_ROM_INVALID,
    ERR_FILE_CLOSE_FAILED,
    ERR_FILE_OPEN_FAILED
} errcode_t;

const char* errcode_to_string_fallback(errcode_t err);

#endif // ERRCODE_H
